name: bb_samba
description: "samba network service"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.0-290.1.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: any

  permission_handler: any
  bonsoir: any
  smb_connect: 
    path: /Users/renanyoy/git/smb_connect

  mime_type: any

  bb.flutter:
    path: /Users/renanyoy/git/bb.flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
